### ISSUE TITLE
ReactDOM.render vs React.render

### ISSUE THREAD

**Issue by MattSturgeon** [meteor/tutorials#15]
As of React version 0.14, DOM stuff like `React.render` is moved into `ReactDOM`

If possible the tutorial should reflect this

**Comment by stubailo** [comment]
Yes! We should update the tutorial. Going to get on it this week.

**Comment by Un3qual** [comment]
Any news on this?

`React.render` works for me, but `React.findDOMNode` needs `ReactDOM.findDOMNode`

**Comment by kamilsmuga** [comment]
@Un3qual before it's fixed in the tutorial, just use ReactDOM in your code as it gets imported automatically.

**Comment by robinnewhouse** [comment]
Any updates? I am still getting the warning containing `Please use ReactDOM.render`

**Comment by stubailo** [comment]
@robinnewhouse have you tried changing your code to use `ReactDOM.render` instead of `React.render`?

**Comment by robinnewhouse** [comment]
Ah, just got it. I didn't realize the `render` that needed fixing was in `simple-todos-react.jsx`. Thanks!

**Comment by lazaridis-com** [comment]
@MattSturgeon @stubailo @abernix - I assume this was fixed? (please close if so)

**Comment by hwillson** [comment]
This was resolved - thanks @lazaridis-com. Closing.
